<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-RaceIQ.Web-4bca7e42-62a6-46cd-9c90-068461e607d5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Data\app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.31" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RaceIQ.Domain\RaceIQ.Domain.csproj" />
    <ProjectReference Include="..\RaceIQ.Application\RaceIQ.Application.csproj" />
    <ProjectReference Include="..\RaceIQ.Infrastructure\RaceIQ.Infrastructure.csproj" />
  </ItemGroup>

</Project>
